

name: (DEV) Build and Deploy

on:
  push:
    branches:
      - develop

jobs:
  # prepare:
  #   runs-on: ubuntu-latest
  #   steps:
      # - name: Tyescript check
      #   run: yarn tsc
      # - name: Prettier check
      #   run: yarn format
      # - name: ESLint check
      #   run: yarn lint
  build:
    # needs: prepare
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Build, tag, and push image to Amazon ECR 🏷
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: "alfie-frontend-v2"
        IMAGE_TAG: develop
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG . --build-arg sendbird_app_id=${{ vars.NEXT_PUBLIC_SENDBIRD_APP_ID }} stripe_publishable_key=${{ env.REACT_APP_STRIPE_PUBLISHABLE_KEY }}
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"